# Example workflow for GitHub Actions
name: Example workflow

# specfiy the trigger for this workflow
on:
  workflow_dispatch:

# group together all jobs that run in the workflow
jobs:
  # define job name
  build:
    # define the type of machine that will process a job
    runs-on: ubuntu-latest

    steps:
    # check out repository
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      with:
        # whether to configure token or SSH key with local git config
        persist-credentials: false

    - name: Run command
      run: echo "Hello, GitHub Actions!"
